env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
settings:
  react:
    version: '18.2.0'
plugins:
  - '@typescript-eslint'
  - react
  - prettier
rules:
  prettier/prettier: error
  react/react-in-jsx-scope: off
  react/prop-types: off
ignorePatterns:
  - node_modules/
  - .next/
  - out/
