services:
  cosmos:
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cosmos
    ports:
      - '3010:3000'
    expose:
      - 3000
    volumes:
      - /mnt/europa/appdata/cosmos:/app
      - /app/node_modules
    restart: unless-stopped
    labels:
      - "traefik.enable: true"
      - "traefik.http.routers.cosmos.entryPoints: https"
    networks:
      - cafepurr
networks:
  cafepurr:
    external: true
    name: cafepurr
    driver: bridge
